### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by aminelazz** [mbahArip/next-gdrive-index#12] opened 2024-04-21 03:18 UTC
Hello  and thank you very much for this beatiful project, i am facing an issue that the content of the root folder is shown, but when i enter to one of the folders it shows this message
![image](https://github.com/mbahArip/next-gdrive-index/assets/84923747/e18f32df-ee72-4bf4-b15f-a5a45af1c434)

When checked the vercel logs it shows this:

```
o [Error]: File not found: 1qIAyBL1w49Xg4JTxFvvVGHA9MuhMjrHX.
    at d._request (/var/task/.next/server/chunks/816.js:1:42991)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async n.requestAsync (/var/task/.next/server/chunks/816.js:10:46188)
    at async et (/var/task/.next/server/app/[...rest]/page.js:28:366543)
```

Note: i've already encrypted the folderID in the config, and changed the env variables and the Vercel's environment variables naming too

**Comment by mbahArip** [comment] 2024-04-21 07:11
1. Have you tried to redeploy the app? Vercel need to redeploy everytime you change environment or serverless region
2. Make sure you've already share the folder with your service account

**Comment by aminelazz** [comment] 2024-04-21 14:30
> 1. Have you tried to redeploy the app? Vercel need to redeploy everytime you change environment or serverless region
> 2. Make sure you've already share the folder with your service account

1. I guess it redeploys everytime i commit something.
2. As i said, it does show the content of the root folder, but when i try to enter to one of the sub folders it shows that error. So it's not a sharing problem 'cause the service account already has access to the root folder.

And thank you for the fast reply, Have a nice day

**Comment by mbahArip** [comment] 2024-04-22 10:22
Now that's a weird one...

Does your folder have the same folder name / file?
Or does the folder are saved inside shared drive?
If it's ok, can you drop your deployment URL here?

**Comment by aminelazz** [comment] 2024-04-22 12:10
> Now that's a weird one...
> 
> Does your folder have the same folder name / file?
> Or does the folder are saved inside shared drive?
> If it's ok, can you drop your deployment URL here?


The root folder that i am using to show its content and the sub-folders have different names.
And yes, it's a shared drive.

Deployment URL (i guess you have to be connected to my account to access it): raws-index-p8k3sm41v-aminelazzs-projects.vercel.app

Production URL: https://raws-index.vercel.app/

**Comment by mbahArip** [comment] 2024-04-22 14:15
It might be shared drive that cause the issues, since I haven't tested it on the v2.
Can you try to use your own drive to check if it's actually the shared drive that causing this error?

**Comment by aminelazz** [comment] 2024-04-22 15:44
> It might be shared drive that cause the issues, since I haven't tested it on the v2. Can you try to use your own drive to check if it's actually the shared drive that causing this error?

I tried a personal drive folder and added the service account, it doesn't show the the root folder content.
![image](https://github.com/mbahArip/next-gdrive-index/assets/84923747/69fab94b-5c8b-45d4-9cf5-221f97c67506)

 But whent i type the name of a subfolder in the URL it shows its content
 
![image](https://github.com/mbahArip/next-gdrive-index/assets/84923747/032cadf6-7cbc-4c45-b486-1d4ef9fceabc)

Which is actually weird lol

**Comment by aminelazz** [comment] 2024-04-22 16:04
> can you try replace the /src/app/actions.ts with the one from the new branch?
After replacing it, the personal drive folder issue has been fixed.

And another error appeared after switching to the shared drive, the vercel logs show:
`Shared drive not found: **the encrypted folder id**`
![image](https://github.com/mbahArip/next-gdrive-index/assets/84923747/da6f73f5-129d-4ad6-a1d5-694f9c513a15)

**Comment by aminelazz** [comment] 2024-04-22 16:57
> Welp.
> It's kinda hard for me to test it.
> I'll search some cheap shared drive for now to test it, expect the fix in couple of days.

No problem, take your time.
And thank you for your assistance, have a nice day

**Comment by mbahArip** [comment] 2024-04-23 05:35
Just got my hand on shared drive.
With quick test, browse, preview, and downloading files work as intended.
But I'll check more thoroughly in the evening (GMT+7) and will merge at midnight if there are no issues.
![image](https://github.com/mbahArip/next-gdrive-index/assets/62494292/4b4eefa4-b54a-4421-b9ff-f36cd272fe2d)

**Comment by mbahArip** [comment] 2024-04-24 13:36
Should be fixed on latest commit.
The demo site should be using the files from my shared drive now if you want to check it.

You need to add the shared drive ID to the `config > apiConfig > sharedDrive` and you need to add your service account to your shared drive member. (If you're not, somehow it won't load the files on root even though it's already inside a new folder)
![image](https://github.com/mbahArip/next-gdrive-index/assets/62494292/abfbf0c0-06a9-4140-8a52-12f6249de285)


If you found any issues, you can create a new issue or reopen this issue.

**Closed** 2024-04-24 13:36 UTC
Labels: bug
