### ISSUE TITLE
Duplicate folder issue

### ISSUE THREAD

**Issue by mioscape** [mbahArip/next-gdrive-index#20] opened 2024-05-15 13:50 UTC
I found issue if theres same folder name in different directory.
Example:
- Folder A/example
- Folder B/example

Somehow, if i open example folder in Folder B, the opened one is from the Folder A

**Comment by mbahArip** [comment] 2024-05-15 18:06
Should be fixed now

![image](https://github.com/mbahArip/next-gdrive-index/assets/62494292/3c25b3b2-e020-42a1-bfdb-1bab3d55d1cd)
![image](https://github.com/mbahArip/next-gdrive-index/assets/62494292/e7c5bb36-5a2a-4949-837a-5406aa013612)

Since I'm still cleaning up the v2 branch, you can check the fix [here](https://github.com/mbahArip/next-gdrive-index/blob/722690ac4dd0cab8df53b2e229808aea8380ef1d/src/app/actions.ts#L110)
**Only replace the CheckPath function**, since there are other difference caused by the cleanup that might be causing issues on main branch

**Closed** 2024-05-15 20:57 UTC
Labels: bug
